### ISSUE TITLE
UnicodeDecodeError using PickleSerializer

### ISSUE THREAD

**Issue by prochanev-thw** [aio-libs/aiocache#534]
Hi, I have same problem how in UnicodeDecodeError with PickleSerializer #515. 
But ask creator already close issue without any answers :(
Error: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte`

i ran example, but added row `print(loop.run_until_complete(cache.get("key")))` after creation cache object.

```import asyncio

from collections import namedtuple

from aiocache import cached, Cache
from aiocache.serializers import PickleSerializer

Result = namedtuple('Result', "content, status")


@cached(
    ttl=10, cache=Cache.REDIS, key="key", serializer=PickleSerializer(), port=6379, namespace="main")
async def cached_call():
    print("Sleeping for three seconds zzzz.....")
    await asyncio.sleep(3)
    return Result("content", 200)


def run():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(cached_call())
    loop.run_until_complete(cached_call())
    loop.run_until_complete(cached_call())
    cache = Cache(Cache.REDIS, endpoint="127.0.0.1", port=6379, namespace="main")
    print(loop.run_until_complete(cache.get("key")))
    loop.run_until_complete(cache.delete("key"))

if __name__ == "__main__":
    run()
```

traceback
```
Traceback (most recent call last):
  File "/home/prochan/prochan-thw-projects/short-url-service/cache_test.py", line 33, in <module>
    run()
  File "/home/prochan/prochan-thw-projects/short-url-service/cache_test.py", line 28, in run
    print(loop.run_until_complete(cache.get("key")))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/prochan/prochan-thw-projects/short-url-service/.venv/lib/python3.8/site-packages/aiocache/base.py", line 61, in _enabled
    return await func(*args, **kwargs)
  File "/home/prochan/prochan-thw-projects/short-url-service/.venv/lib/python3.8/site-packages/aiocache/base.py", line 45, in _timeout
    return await asyncio.wait_for(func(self, *args, **kwargs), timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/home/prochan/prochan-thw-projects/short-url-service/.venv/lib/python3.8/site-packages/aiocache/base.py", line 75, in _plugins
    ret = await func(self, *args, **kwargs)
  File "/home/prochan/prochan-thw-projects/short-url-service/.venv/lib/python3.8/site-packages/aiocache/base.py", line 192, in get
    value = loads(await self._get(ns_key, encoding=self.serializer.encoding, _conn=_conn))
  File "/home/prochan/prochan-thw-projects/short-url-service/.venv/lib/python3.8/site-packages/aiocache/backends/redis.py", line 24, in wrapper
    return await func(self, *args, _conn=_conn, **kwargs)
  File "/home/prochan/prochan-thw-projects/short-url-service/.venv/lib/python3.8/site-packages/aiocache/backends/redis.py", line 102, in _get
    return await _conn.get(key, encoding=encoding)
  File "/home/prochan/prochan-thw-projects/short-url-service/.venv/lib/python3.8/site-packages/aioredis/connection.py", line 234, in _process_data
    obj = decode(obj, encoding)
  File "/home/prochan/prochan-thw-projects/short-url-service/.venv/lib/python3.8/site-packages/aioredis/util.py", line 45, in decode
    return obj.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

in redis i have `\x80\x04\x95'\x00\x00\x00\x00\x00\x00\x00\x8c\b__main__\x94\x8c\x06Result\x94\x93\x94\x8c\acontent\x94K\xc8\x86\x94\x81\x94.` string with key `main:key.`

We have some restrictions with `PickleSerializer`?

**Comment by Dreamsorcerer** [comment]
The exception comes from aioredis, and we've now migrated to latest redis library.
So, please test on master or 0.12 release, and reopen if still an issue.
